spring.application.name=backend
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/elm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
<<<<<<< HEAD
=======

spring.datasource.username=root
spring.datasource.password=
>>>>>>> origin/main

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=never
    